  # ============================================================
  # SET BASE VARIABLES
  # ============================================================

  - name: Set base AWS variables
    ansible.builtin.set_fact:
      assume_role_instance: localhost
      aws_region: us-east-1
      sts_role_name: BSLOPS-Automation
      aws_accounts:
        - { account_id: 720731127848, location: "AWS EMEA Non-Prod VPC" }
        - { account_id: 007887086890, location: "AWS EMEA Shared Services VPC" }
        - { account_id: 954976326790, location: "AWS EMEA Production VPC" }
        - { account_id: 877009147629, location: "AWS Ireland - GIO PROD VPC" }
        - { account_id: 410477946908, location: "AWS Ireland - GIO NON-PROD" }
        - { account_id: 749491338664, location: "AWS Ireland - GIO SHARED" }

  # ============================================================
  # READ HOST / SURVEY VARIABLES
  # ============================================================

  - name: Read input variables
    ansible.builtin.set_fact:
      resource_type: "{{ resource_type | default('ec2') }}"
      aws_instance_id_raw: "{{ inst_id | default([]) }}"
      rds_db_identifier_raw: "{{ db_instance_id | default([]) }}"
      rds_cluster_identifier_raw: "{{ db_cluster_id | default([]) }}"
      aws_location: "{{ location | default('') }}"
      ec2_action: "{{ ec2_action | default('') }}"

  # ============================================================
  # NORMALIZE INPUT (Supports list OR comma-separated survey input)
  # ============================================================

  - name: Normalize EC2 list
    ansible.builtin.set_fact:
      aws_instance_ids: >-
        {{
          aws_instance_id_raw if aws_instance_id_raw is iterable and aws_instance_id_raw is not string
          else aws_instance_id_raw.split(',') if aws_instance_id_raw | length > 0
          else []
        }}

  - name: Normalize RDS list
    ansible.builtin.set_fact:
      rds_db_identifiers: >-
        {{
          rds_db_identifier_raw if rds_db_identifier_raw is iterable and rds_db_identifier_raw is not string
          else rds_db_identifier_raw.split(',') if rds_db_identifier_raw | length > 0
          else []
        }}

  - name: Normalize Aurora list
    ansible.builtin.set_fact:
      rds_cluster_identifiers: >-
        {{
          rds_cluster_identifier_raw if rds_cluster_identifier_raw is iterable and rds_cluster_identifier_raw is not string
          else rds_cluster_identifier_raw.split(',') if rds_cluster_identifier_raw | length > 0
          else []
        }}

  # ============================================================
  # VALIDATION
  # ============================================================

  - name: Validate action
    ansible.builtin.fail:
      msg: "ec2_action must be started, stopped, or restarted"
    when: ec2_action not in ["started", "stopped", "restarted"]

  - name: Validate resource selection
    ansible.builtin.fail:
      msg: "No valid resource identifiers provided for selected resource_type"
    when: >
      (resource_type == "ec2" and aws_instance_ids | length == 0) or
      (resource_type == "rds" and rds_db_identifiers | length == 0) or
      (resource_type == "aurora" and rds_cluster_identifiers | length == 0)

  # ============================================================
  # MAP LOCATION → ACCOUNT ID
  # ============================================================

  - name: Resolve AWS account ID
    ansible.builtin.set_fact:
      aws_account_id: "{{ item.account_id }}"
    loop: "{{ aws_accounts }}"
    when: item.location == aws_location

  - name: Fail if account not mapped
    ansible.builtin.fail:
      msg: "No AWS account mapping found for location: {{ aws_location }}"
    when: aws_account_id is not defined

  # ============================================================
  # ASSUME ROLE
  # ============================================================

  - name: Assume role in target AWS account
    amazon.aws.sts_assume_role:
      role_arn: "arn:aws:iam::{{ aws_account_id }}:role/{{ sts_role_name }}"
      role_session_name: "AWX-Automation-Session"
      region: "{{ aws_region }}"
    register: assumed_role
    no_log: true
    delegate_to: "{{ assume_role_instance }}"

  # ============================================================
  # CONVERT RESTART FOR RDS/AURORA
  # ============================================================

  - name: Convert restart to reboot for RDS
    ansible.builtin.set_fact:
      rds_state: "{{ 'rebooted' if ec2_action == 'restarted' else ec2_action }}"
    when: resource_type in ["rds", "aurora"]

  # ============================================================
  # EC2 MANAGEMENT (MULTIPLE SUPPORTED)
  # ============================================================

  - name: Manage EC2 instances
    amazon.aws.ec2_instance:
      region: "{{ aws_region }}"
      instance_ids: "{{ aws_instance_ids }}"
      state: "{{ ec2_action }}"
      wait: true
    environment:
      AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
      AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
    delegate_to: localhost
    when: resource_type == "ec2"

  - name: Display EC2 summary
    ansible.builtin.debug:
      msg: "EC2 instances {{ aws_instance_ids }} processed with action {{ ec2_action }}"
    when: resource_type == "ec2"

  # ============================================================
  # RDS INSTANCE MANAGEMENT (MULTIPLE SUPPORTED)
  # ============================================================

  - name: Manage RDS instances
    amazon.aws.rds_instance:
      db_instance_identifier: "{{ item }}"
      state: "{{ rds_state }}"
      region: "{{ aws_region }}"
      wait: true
    loop: "{{ rds_db_identifiers }}"
    environment:
      AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
      AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
    delegate_to: localhost
    when: resource_type == "rds"

  - name: Display RDS summary
    ansible.builtin.debug:
      msg: "RDS instances {{ rds_db_identifiers }} processed with action {{ ec2_action }}"
    when: resource_type == "rds"

  # ============================================================
  # AURORA CLUSTER MANAGEMENT (MULTIPLE SUPPORTED)
  # ============================================================

  - name: Manage Aurora clusters
    amazon.aws.rds_cluster:
      db_cluster_identifier: "{{ item }}"
      state: "{{ rds_state }}"
      region: "{{ aws_region }}"
      wait: true
    loop: "{{ rds_cluster_identifiers }}"
    environment:
      AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
      AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
    delegate_to: localhost
    when: resource_type == "aurora"

  - name: Display Aurora summary
    ansible.builtin.debug:
      msg: "Aurora clusters {{ rds_cluster_identifiers }} processed with action {{ ec2_action }}"
    when: resource_type == "aurora"

  # ============================================================
  # RDS 7-DAY AUTO-START WARNING
  # ============================================================

  - name: Warn about 7-day RDS auto restart
    ansible.builtin.debug:
      msg: "WARNING: RDS automatically starts after 7 days if stopped."
    when:
      - ec2_action == "stopped"
      - resource_type in ["rds", "aurora"]
